### ISSUE TITLE
Username Mismatch in Repository Name

### ISSUE THREAD

**Issue by Kushhhhhhhh** [Khushi-dubey-dot/Khushi-dubey-dot#1]
Hi Khushi,

I've noticed that the repository name currently displays "Khushi-Dubey" instead of "Khushi-dubey-dot" in the username. Due to this, it seems like there's a mismatch that might prevent some functionality from working properly.
Could you please update the repository name to "Khushi-dubey-dot"? This should resolve the issue.

Thank you for your hard work and the contributions you’ve made with this repository! Looking forward to seeing this resolved.

Best regards,
Kush Sharma

**Comment by Khushi-dubey-dot** [comment]
Thank You for the Feedback on the Repository Name

Hi Kush,

Thank you for pointing out the mismatch in the repository name. I truly
appreciate your attention to detail. I’ll go ahead and update the
repository name to "Khushi-dubey-dot" to ensure everything works smoothly.

Thanks again for your guidance, and I’m glad to contribute to this project!

Best regards,
Khushi Dubey
